const express = require('express');
const router = express.Router();
const { getDashboardStats, getAllUsers, getAllVolunteers, verifyVolunteer, toggleUserStatus, getReports } = require('../controllers/adminController');
const { protect, authorize } = require('../middleware/auth');
router.use(protect, authorize('admin'));
router.get('/stats', getDashboardStats);
router.get('/users', getAllUsers);
router.put('/users/:id/toggle', toggleUserStatus);
router.get('/volunteers', getAllVolunteers);
router.put('/volunteers/:id/verify', verifyVolunteer);
router.get('/reports', getReports);
module.exports = router;
